version: '3.4'

services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    ports:
        - 27017:27017

  koaaapp:
    image: "koaapp:${DOCKER_TAG:-latest}"
    container_name: "koaapp"
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 80
    ports:
      - "5001:80"
    links:
      - mongo
    volumes:
     - ./src:/app/src